---
Name: fromholdio-errorpagesconfig
---
SilverStripe\ErrorPage\ErrorPage:
  hide_ancestor: SilverStripe\ErrorPage\ErrorPage
  extensions:
    - Fromholdio\ErrorPagesConfig\Extensions\ErrorPageExtension
  summary_fields:
    - Title
    - CodeLabel
  field_labels:
    CodeLabel: 'Error Code'
  default_sort: 'ErrorCode'
SilverStripe\ORM\Hierarchy\Hierarchy:
  hide_from_cms_tree:
    - SilverStripe\ErrorPage\ErrorPage
---
Only:
  classexists: 'Symbiote\Multisites\Multisites'
---
Symbiote\Multisites\Model\Site:
  extensions:
    - Fromholdio\ErrorPagesConfig\Extensions\SiteExtension
---
Except:
  classexists: 'Symbiote\Multisites\Multisites'
---
Silverstripe\SiteConfig\SiteConfig:
  extensions:
    - Fromholdio\ErrorPagesConfig\Extensions\SiteConfigExtension
